[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "weakget"
author = "Sye van der Veen"
author-email = "syeberman@gmail.com"
home-page = ""
classifiers = ["License :: Public Domain"]
